package service

import (
	"context"

	generalv1 "github.com/coding-standard/golang-project-layout/api/general/v1"
	projectv1 "github.com/coding-standard/golang-project-layout/api/golang-project-layout/v1"
	"github.com/coding-standard/golang-project-layout/internal/dao"
	"github.com/coding-standard/golang-project-layout/pkg/utils"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/emptypb"
)

type DemoDbService struct {
	// This is generated by protoc
	projectv1.UnimplementedDemoDbServer
	// Remove follow line if you don't need database operate
	dao dao.DemoDbDao
}

func NewDemoDbService(dao dao.Interface) *DemoDbService {
	return &DemoDbService{dao: dao.DemoDbDao()}
}

func (s *DemoDbService) Token(ctx context.Context, req *emptypb.Empty) (*generalv1.TokenResponse, error) {
	accessToken, _, errGenTokens := utils.GenerateTokens(1)
	if errGenTokens != nil {
		return nil, errGenTokens
	}
	return &generalv1.TokenResponse{
		Token: accessToken,
	}, nil
}

func (s *DemoDbService) DemoDb(ctx context.Context, req *generalv1.DemoDbRequest) (*generalv1.DemoDbResponse, error) {
	claims, err := utils.GetTokenDetails(ctx)
	if err != nil {
		return nil, status.Error(codes.Unauthenticated, err.Error())
	}
	demoDb, err := s.dao.DemoDb(ctx, req.DemoDb)
	if err != nil {
		result := status.Convert(err)
		if result.Code() == codes.NotFound {
			return nil, status.Errorf(codes.NotFound, "get err: %s not found", req.DemoDb)
		}
		return nil, status.Error(codes.Unknown, err.Error())
	}
	return &generalv1.DemoDbResponse{
		DemoDb: &generalv1.DemoDb{
			Id:     int64(claims.ID),
			DemoDb: demoDb.DemoDb,
		},
	}, nil
}
